/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARRAY_SUM_H_RPCGEN
#define _ARRAY_SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int size;
	int array[100];
};
typedef struct data data;

#define ARRAY_SUM 0x23451111
#define SUM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define arr_sum 1
extern  int * arr_sum_1(data *, CLIENT *);
extern  int * arr_sum_1_svc(data *, struct svc_req *);
extern int array_sum_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define arr_sum 1
extern  int * arr_sum_1();
extern  int * arr_sum_1_svc();
extern int array_sum_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARRAY_SUM_H_RPCGEN */
