/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "array_sum.h"


void
array_sum_1(char *host, int arr[], int n)
{
	CLIENT *clnt;
	int  *result_1;
	data  arr_sum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARRAY_SUM, SUM_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */
	for (int i = 0; i < n; i ++)
		arr_sum_1_arg.array[i] = arr[i];
	arr_sum_1_arg.size = n;

	result_1 = arr_sum_1(&arr_sum_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Sum: %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host ARRAY_SIZE\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int size = atoi(argv[2]);
	int arr[size];
	for (int i = 0; i < size; i ++)
		scanf("%d", &arr[i]);
	array_sum_1 (host,arr, size);
exit (0);
}
