/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "array_sum.h"

int *
arr_sum_1_svc(data *argp, struct svc_req *rqstp)
{
	static int  result;

	int size = argp->size;
	int sum = 0;
	for (int i = 0; i < size; i++)
		sum += argp->array[i];

	result = sum;

	return &result;
}
