/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct param {
	char data[1000];
};
typedef struct param param;

#define NFS_PROG 0x23451111
#define NFS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define readFile 1
extern  param * readfile_1(param *, CLIENT *);
extern  param * readfile_1_svc(param *, struct svc_req *);
extern int nfs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define readFile 1
extern  param * readfile_1();
extern  param * readfile_1_svc();
extern int nfs_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param (XDR *, param*);

#else /* K&R C */
extern bool_t xdr_param ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
