/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


void
nfs_prog_1(char *host, char fname[])
{
	CLIENT *clnt;
	param  *result_1;
	param  readfile_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NFS_PROG, NFS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int n = strlen(fname);
	printf("Requesting file: %s\n", fname);
	int i = 0;
	for (; i < n; i ++)
		readfile_1_arg.data[i] = fname[i];
	readfile_1_arg.data[i] = '\0';
	result_1 = readfile_1(&readfile_1_arg, clnt);
	if (result_1 == (param *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("File contents: %s\n", result_1->data);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host FILE_NAME\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nfs_prog_1 (host, argv[2]);
exit (0);
}
