/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
param *
readfile_1_svc(param *argp, struct svc_req *rqstp)
{
	static param  result;

	printf("File name: %s\n", argp->data);
	int i = 0;
	int fd; char ch;
	fd = open(argp->data, 'r');
	if (fd < 0)
		perror("hag diya");
	dup2(fd,0);
	while (scanf("%c",&ch)>0) {
		result.data[i++] = ch;
	}

	return &result;
}
