/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"

long *
getlongtime_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  result;

	long time();
	printf("getlongTime called\n");
	result = time((long*)0);

	return &result;
}

char **
getstrdate_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;
	char *ctime();
	printf("getstrDate called\n");
	result = ctime(argp);

	return &result;
}
