/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DATE_PROG 0x23451111
#define DATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getlongTime 1
extern  long * getlongtime_1(void *, CLIENT *);
extern  long * getlongtime_1_svc(void *, struct svc_req *);
#define getStrDate 2
extern  char ** getstrdate_1(long *, CLIENT *);
extern  char ** getstrdate_1_svc(long *, struct svc_req *);
extern int date_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getlongTime 1
extern  long * getlongtime_1();
extern  long * getlongtime_1_svc();
#define getStrDate 2
extern  char ** getstrdate_1();
extern  char ** getstrdate_1_svc();
extern int date_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATE_H_RPCGEN */
