/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfsdir.h"


void
nfsdir_prog_1(char *host, char dirname[100])
{
	CLIENT *clnt;
	output  *result_1;
	input  lsdir_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NFSDIR_PROG, DIR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	strcpy(lsdir_1_arg.data, dirname);
	result_1 = lsdir_1(&lsdir_1_arg, clnt);
	if (result_1 == (output *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("%s\n", result_1->data);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host DIRECTORY_NAME\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nfsdir_prog_1 (host, argv[2]);
exit (0);
}
